server:
  port: 8081
spring:
  application:
    name: "user-services"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: jdbc:postgresql://localhost:5432/neofile_db
    username: neofile_user
    password: neofile_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: users_schema
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"
