server:
  port: 8080
spring:
  application:
    name: "user-services"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: "jdbc:h2:mem:test"
    username: "sa"
    password: "pass"
    driver-class-name: "org.postgresql.Driver"
    liquibase:
      enabled: true
      change-log: "classpath:db/changelog/db.changelog-master.yaml"
    jpa:
      hibernate:
        ddl-auto: "none"
    driverClassName: "org.h2.Driver"
  profiles:
    include: null
  jpa:
    databasePlatform: "org.hibernate.dialect.H2Dialect"
