version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: neofile_postgres
    restart: always
    environment:
      POSTGRES_USER: neofile_user
      POSTGRES_PASSWORD: neofile_pass
      POSTGRES_DB: neofile_db
    ports:
      - "5432:5432"
    volumes:
      - neofile_pgdata:/var/lib/postgresql/data
    networks:
      - neofile_network

volumes:
  neofile_pgdata:

networks:
  neofile_network:
    driver: bridge
